### ISSUE TITLE
Makefile not using correct version of go-swagger

### ISSUE THREAD

**Issue by codenrhoden** [emccode/gorackhd#19]
I noticed today that the generated client code wasn't using the vendored version of go-swagger.  When doing a `make`, I would see:

`go run /Users/travis/go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go generate client -f swagger-spec/monorail.yml`

But I expected to see:

`go run vendor/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go generate client -f swagger-spec/monorail.yml`

I expected this because we are vendoring go-swagger to get a specific version.  However, looking at commit history, I see that @akutz  did this on purpose in https://github.com/emccode/gorackhd/commit/3c0f1fb5bda9770f4d8febb89fabfaeb7468a146. The intent was to go use go-swagger out of the GOPATH, as it fixes some invalid import paths that get put in when using a vendored go-swagger.  To quote:

> files generated using a vendored
> version of swagger would be corrupt, containing incorrect import paths.
> This fix changes the behavior of glide to copy vendored packages during
> the first phase of the build process into the standard GOPATH structure.
> Then the bindings are built by executing the swagger command's source
> file using `go run` from inside the GOPATH structure.

However, it does not appear that Glide sets the version of go-swagger in $GOPATH as called for in the YAML file.

Here is an example, using the current `master` branch:

```
[travis@mbp ~/go/src/github.com/emccode/gorackhd (master)]$ make clean
rm -fr glide.lock .go.get cover.out client models
[travis@mbp ~/go/src/github.com/emccode/gorackhd (master *)]$ make clobber-gopath-swagger
rm -fr /Users/travis/go/bin/swagger
rm -fr /Users/travis/go/src/github.com/go-swagger/go-swagger
rm -fr /Users/travis/go/pkg/*/github.com/go-swagger/go-swagger
[travis@mbp ~/go/src/github.com/emccode/gorackhd (master *)]$ cat glide.yaml
package: github.com/emccode/gorackhd
import:
  - package: github.com/go-swagger/go-swagger
    ref:     6b712512cbe1f1a4882354856b57c61d760499cc
    vcs:     git
[travis@mbp ~/go/src/github.com/emccode/gorackhd (master *)]$ cat glide-swagger.yaml
package: github.com/emccode/gorackhd
ignore:
- client
- models
import:
  - package: github.com/go-swagger/go-swagger
    ref:     6b712512cbe1f1a4882354856b57c61d760499cc
    vcs:     git
[travis@mbp ~/go/src/github.com/emccode/gorackhd (master *)]$ make
....
....
[travis@mbp ~/go/src/github.com/emccode/gorackhd (master *)]$ pushd vendor/github.com/go-swagger/go-swagger/
~/go/src/github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger ~/go/src/github.com/emccode/gorackhd
[travis@mbp ~/go/src/github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger ((6b71251...))]$ git status
HEAD detached at 6b71251
nothing to commit, working directory clean
[travis@mbp ~/go/src/github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger ((6b71251...))]$ popd
~/go/src/github.com/emccode/gorackhd
[travis@mbp ~/go/src/github.com/emccode/gorackhd (master *)]$ pushd ../../go-swagger/go-swagger/
~/go/src/github.com/go-swagger/go-swagger ~/go/src/github.com/emccode/gorackhd
[travis@mbp ~/go/src/github.com/go-swagger/go-swagger (master)]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

Note that `go-swagger` in the $GOPATH is on **master**.  That's not what we were after.

The command we expect to do this for us is `/Users/travis/go/bin/glide --home /Users/travis --yaml glide-swagger.yaml up --quick --cache-gopath --use-gopath`

`--cache-gopath` will copy the git repo from the $GOPATH into vendor if it's there.
`--use-gopath` will also download a dependency into $GOPATH (presumably to take better advantage of caching).  But, AFAICT this does _not_ set the version. And truthfully I don't think it should. Glide is for managing deps in the vendor dir, I wouldn't want it changing versions of repos in my $GOPATH...

So either (1) this is a bug in Glide and it should set that version (I don't think it should) or (2) this approach doesn't quite work.

I'd be curious to know more about what issues were hit  when generating the client from the vendored version of `go-swagger`. I had edited the Makefile locally to use the vendored version instead, and the code looked fine. All tests passed, but those aren't exercising a whole lot. Is there any advice on how I could look if those invalid import paths are still being generated? Because if they aren't, we can simplify this whole thing by using the vendored version again.

FYI, I had pushed a branch, `fix/use_vendored_swagger` that uses the vendored go-swagger instead, but that was before I found the history. The cleaner way to structure the Makefile would be to put it how @akutz had it before adding the GOPATH swagger.

**Comment by codenrhoden** [comment]
Found this as a bit helpful: https://github.com/Masterminds/glide/issues/178

It doesn't directly address whether a version should be set with `--use-gopath`, but I almost feel like it's omission confirms it. I could comment and ask.

**Comment by kacole2** [comment]
@codenrhoden as a bit of background. we versioned go-swagger because it's in rapid development and using the tip of master against the `monorail.yml` could have led to unexpected generated code. 

I honestly think we are spending time in the wrong parts. At the end of the day, all we need is the generated code

**Comment by codenrhoden** [comment]
@kacole2 I understand the background and agree with it. But the intent was not realized. The tip of master is and was being used since 3c0f1fb.  We can continue to do as much, but then the Makefile can be simplified quite a bit.

I'll proceed with the other changes I have queued up, using go-swagger from master. But I'd like to leave this open until we make a change. Right now the build uses a two-phase approach to solve a problem, but it is not solving that problem.

The right time to lock things down again would probably by when `go-swagger` 0.6.0 is released.
